---
- name: Install any necessary dependencies (git, python related packages)
  apt:
    name:
      - git
      - python-virtualenv # `bitdust install` doesn't work without `virtualenv` command
      - python3-pip
      - python3-virtualenv
      - python3-dev
      - gcc
      - libssl-dev
      - libffi-dev
      - build-essential
    state: present
    update_cache: yes
    cache_valid_time: 3600
  register: apt_result
  until: apt_result is success
  retries: 2
  delay: 5

- name: Install bitdust from devel
  git:
    repo: https://github.com/bitdust-io/devel.git
    dest: /home/bitdust/public
    force: yes
#    version: 121c07f1267b78b0924a6f97bc424dc15f640a71

- name: Check that bitdust installed
  stat:
    path: "{{ ansible_env.HOME }}/.bitdust/installed"
  register: bitdust_installed

- name: Setup bitdust
  shell: python3 bitdust.py install
  args:
      chdir: /home/bitdust/public
  when: bitdust_installed.stat.exists == False

- name: Left artifact of installation
  copy:
    content: "1"
    dest: "{{ ansible_env.HOME }}/.bitdust/installed"

- name: Ensure {{ ansible_env.HOME }}/.bitdust/metadata dir exists
  file: path={{ ansible_env.HOME }}/.bitdust/metadata state=directory

- name: Deploy configuration file with network
  copy:
    content: "{{ lookup('template', 'roles/bitdust/templates/network.j2.json') }}"
    dest: "{{ ansible_env.HOME }}/.bitdust/metadata/networks.json"

- name: Change network to test one
  copy:
    content: "testing"
    dest: "{{ ansible_env.HOME }}/.bitdust/metadata/networkname"

- name: Create a symbolic link for bitdust
  file:
    src: "{{ ansible_env.HOME }}/.bitdust/bitdust"
    dest: /usr/local/bin/bitdust
    state: link

- name: Start bitdust
  shell: bitdust detach
