- hosts: all
  become: true
  vars_files:
    - roles/telegraf/defaults/main.yml
    - roles/telegraf/vars/main.yml
    - "roles/telegraf/vars/{{ application_name }}.yml"
  tasks:
    - include: roles/telegraf/tasks/main.yml
  handlers:
    - include: roles/telegraf/handlers/main.yml
